content:
  - name: header
    label: Header
    path: src/data/user.json
    type: file
    fields:
      - name: name
        label: Full name
        type: text
        options:
          rows: 1
      - name: profession
        label: Profession (tagline)
        type: text
        options:
          rows: 1
  - name: links
    label: Links
    path: src/data/user.json
    type: file
    list: true
    fields:
      - name: url
        label: Target URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$